server:
  port: 14000
spring:
  main:
#    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: zck-iot-gateway
#  profiles:
#    active:
#      - register
#      - redis