server:
  port: 14000
spring:
  cloud:
    function:
      definition: onBlackIpChange;onForbiddenPathChange
    stream:
      bindings:
        onBlackIpChange-in-0:
          destination: zckblackipchange
          group: group1
        onForbiddenPathChange-in-0:
          destination: zckforbiddenpathchange
          group: group2
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: zck-iot-gateway
  profiles:
    active:
      - register
      - redis
      - rabbitmq