spring:
  cloud:
  profiles:
    active:
      - register
      - rabbitmq
  application:
    name: zck-iot-blackip
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///dc3?useUnicode=false&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 15000