server:
  port: 22000
spring:
  application:
    name: zck-iot-tenant
  r2dbc:
    url: r2dbc:mysql://localhost:3306/dc3?SSL=false&sslMode=DISABLED
    username: root
    password: root
  profiles:
    active:
      - register

